jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 8081
   servlet:
      context-path: /Inventario
      session:
         timeout: 21600s

spring:
   datasource:
      driver-class-name: org.postgresql.PGConnection
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:postgresql://localhost/ADN
      username: admin
      password: adminadmin
      hikari:
         poolName: pool
